FROM python:3.7.3-alpine3.9

RUN mkdir -p /home/alex/test/app
WORKDIR /home/alex/test/app

COPY ./requirements.txt /home/alex/test/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./ /home/alex/test/app/
ENV FLASK_APP=server.py

CMD flask run -h 0.0.0.0 -p 5000
